;; example application for Sagittarius NGINX
(library (webapp)
    (export run)
    (import (rnrs)
	    (sagittarius nginx)
	    (rfc :5322)
	    (pp))

(define (run request response) 
  (define out (transcoded-port (nginx-response-output-port response)
			       (native-transcoder)))
  (put-string out "Test web application!!\n")
  (put-string out (nginx-request-method request)) (newline out)
  (put-string out (nginx-request-uri request)) (newline out)
  (put-string out (nginx-request-user-agent request)) (newline out)
  (cond ((nginx-request-content-type request) =>
	 (lambda (v) (put-string out v) (newline out))))
  (cond ((rfc5322-header-ref (nginx-request-headers request) "accept") =>
	 (lambda (v) (put-string out v) (newline out))))
  (pp (nginx-request-headers request) out)
  (let ((bv (get-bytevector-all (nginx-request-input-port request))))
    (unless (eof-object? bv) (put-string out (utf8->string bv))))
  (nginx-response-header-add! response "Date" "date date")
  (nginx-response-header-add! response "Location" "/location")
  (nginx-response-header-add! response "Blar" "blar1")
  (nginx-response-header-add! response "Blar" "blar2")
  (nginx-response-header-set! response "Baz" "baz0")
  (nginx-response-header-remove! response "Baz")
  (nginx-response-header-set! response "Baz" "baz1")
  (nginx-response-header-set! response "Baz" "baz2")

  (pp (nginx-response-headers response) out)
  (values 200 'text/plain))

)
